### PR TITLE
Add missing pointer rederivation in realloc

### PR DESCRIPTION
**Pull request by lucpt**
Rederive the internal pointer when moving the allocation.
This change complements nwf's previous commit db464443.

### CODE REVIEW

**Comment by nwf** [comment]
Sorry, I must be dense; what's the functional impact of this change?  It looks like it's going to just be using the privileged pointer in memcpy, but if we're reaching out of the original bounds, aren't we doing something wrong?

**Comment by nwf** [comment]
**OH!** Is the problem that the original bounds might be less than the size-class size computed by `alloc_size`?  Right, yes, I can see how that would explode.  Let me draft a patch for your assessment.

**Comment by nwf** [comment]
How do you feel about https://github.com/nwf/snmalloc/tree/lucpt-realloc ?

**Comment by nwf** [comment]
I went ahead and merged to master.  There's another fix to realloc there, too.

**Comment by lucpt** [comment]
This will do, and I think it is a reasonable caller treatment

**Pull request closed without merging**
